### ISSUE TITLE
Uncaught Error: Element ref was specified as a string (message) but no owner was set

### ISSUE THREAD

**Issue by cosmin220304** [Detaysoft/react-chat-elements#158] opened 2021-12-31 15:12 UTC
Hi,

I get the following error when trying to use  [MessageList](https://www.npmjs.com/package/react-chat-elements#messagelist-component) from documentation (note: even without any change from documentation)

```
react-dom.development.js:13218 Uncaught Error: Element ref was specified as a string (message) but no owner was set. This could happen for one of the following reasons:
1. You may be adding a ref to a function component
2. You may be adding a ref to a component that was not created inside a component's render method
3. You have multiple copies of React loaded
See https://reactjs.org/link/refs-must-have-owner for more information.
    at coerceRef (react-dom.development.js:13218)
    at reconcileSingleElement (react-dom.development.js:14054)
    at reconcileChildFibers (react-dom.development.js:14112)
    at reconcileChildren (react-dom.development.js:16990)
    at finishClassComponent (react-dom.development.js:17511)
    at updateClassComponent (react-dom.development.js:17435)
    at beginWork (react-dom.development.js:19073)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
```

Anyone got any fix for this? 
![screenshot](https://user-images.githubusercontent.com/1769806/147849215-34bc9948-9d18-4ef9-80dc-3578a82924ef.png)
![screenshot2](https://user-images.githubusercontent.com/1769806/147829931-6829cb3e-5270-43dc-8664-bdb557be1b14.jpg)

**Comment by cosmin220304** [comment] 2022-01-01 11:12
Same error for MessageBox component

**Comment by faseehjaved** [comment] 2022-01-08 22:39
if you are using react version other than 16 then this error may be due to multiple copies of react. try `npm ls react`. react-chat-elements is using react version 16.14.0 so the conflict occurs.

**Comment by utopictown** [comment] 2022-01-11 14:23
i got same issue

**Comment by IgorSurzhko** [comment] 2022-01-28 19:39
Is there some solution for different react versions?
<img width="567" alt="Screen Shot 2022-01-28 at 21 37 28" src="https://user-images.githubusercontent.com/42876869/151610652-a7eff5aa-a401-478c-8235-254009ade870.png">

**Comment by emregudur** [comment] 2022-02-23 13:34
Hi guys, this problem is about you are probably using function component, we tried to change MessageBox and MessageList components class component to function component and this fixed the problem. You can use class component instead of function component for react-chat-elements components to the fast solution.

**Comment by vahid-neuralinc** [comment] 2022-02-25 10:28
I have converted my components from function components to class components, but I still face the same error. Looks like that the issue is related to datasource property. If I remove it the error is gone, but off course the component will render blank.

Below is the code of my component:

```
import 'react-chat-elements/dist/main.css';
import { Component } from 'react';

import { MessageBox } from 'react-chat-elements'

export class Chat extends Component {
    constructor(props) {
        super(props);

        this.date = new Date();
    }
    render() {
        
        return (            
            <MessageBox
                position={'left'}
                type={'photo'}
                text={'react.svg'}
                data={{
                    uri: 'https://facebook.github.io/react/img/logo.svg',
                    status: {
                        click: false,
                        loading: 0,
                    }
                }}
            />
        );
    }
};
```

Note that this component is directly added to a route inside App component. My app component is also a class component.

**Comment by emregudur** [comment] 2022-02-25 13:16
Hi, we tried to change components on react-chat-elements and you can see [here](https://github.com/Detaysoft/react-chat-elements/commit/e4cbdd566f2c6fae8b665ce33d648bab14602802).

We works on this problem and as soon as possible aim to fix this problem.

**Comment by vahid-neuralinc** [comment] 2022-02-25 15:22
@emregudur Thank you very much. Anxiously waiting for the fix :)

**Comment by emregudur** [comment] 2022-03-09 14:44
Hi guys, this problem fixed on the new version. Checkout here pls [click](https://www.npmjs.com/package/react-chat-elements/v/11.0.0)

**Closed by emregudur** 2022-03-09 14:44 UTC

**Comment by vahid-neuralinc** [comment] 2022-03-09 14:58
Hi @emregudur Thank you very much. Super amazing.

**Comment by wnmolit** [comment] 2022-03-09 15:34
![Screen Shot 2022-03-09 at 11 29 41 PM](https://user-images.githubusercontent.com/40918539/157473842-7c7439da-dfa9-4905-85ac-2d36eebd4883.png)

I got an error after installing the latest version of this library.

I have the following packages:

`"react-chat-elements": "^11.0.0"`
`"react": "^17.0.2"`
`"react-dom": "^17.0.2"`

Here is my functional component:

```
import React, { useState } from "react";
import {
    Grid,
    Button
} from "semantic-ui-react";
import { 
    ChatList,
    MessageList
} from "react-chat-elements";

const Row = Grid.Row;
const Column = Grid.Column;

import style from "styles/main.module.scss";
import "react-chat-elements/dist/main.css";

const Chat = (props) => {

    const [chatSessionArray, setChatSessionArray] = useState([
        {
            avatar: "/static/images/ic_sample.png",
            alt: "avatar",
            title: "Group 1",
            date: new Date(),
            unread: 0
        },
        {
            avatar: "/static/images/ic_sample.png",
            alt: "avatar",
            title: "Group 2",
            date: new Date(),
            unread: 0
        }
    ]);

    const [chatMessageArray, setChatMessageArray] = useState([
        {
            position: "right",
            type: "text",
            text: "sample message 1",
            date: new Date()
        }
    ]);

    const messageListReferance = React.useRef();

    return (
        <div
            className={ style.chatContainer }>
            <Grid
                divided="vertically">
                <Row
                    columns={ 2 }>
                    <Column
                        width={ 4 }
                        className={ style.chatSession }>
                        {
                            chatSessionArray != 0
                                ? (
                                    <ChatList
                                        dataSource={ chatSessionArray }/>
                                )
                                : ""
                            
                        }
                    </Column>
                    <Column
                        width={ 12 }
                        className={ style.chatMessages }>
                        {
                            chatMessageArray.length != 0
                                ? (
                                    <MessageList
                                        referance={ messageListReferance }
                                        toBottomHeight={ "100%" }
                                        dataSource={ chatMessageArray }/>
                                )
                                : ""
                        }
                    </Column>
                </Row>
            </Grid>
        </div>
    );

}

export default Chat;
```
